// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Sl3arszQfXR2BbbERZTlMcb1Luqf-78',
    appId: '1:571042995828:web:ec9940316fb5fe9531bb21',
    messagingSenderId: '571042995828',
    projectId: 'clone-tiktok-uryuryuc',
    authDomain: 'clone-tiktok-uryuryuc.firebaseapp.com',
    storageBucket: 'clone-tiktok-uryuryuc.appspot.com',
    measurementId: 'G-8TZ9N0DM8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChLTM94W9QZDK-eUB8X02m6C-3GHvUHoE',
    appId: '1:571042995828:android:9243834e3002d9ed31bb21',
    messagingSenderId: '571042995828',
    projectId: 'clone-tiktok-uryuryuc',
    storageBucket: 'clone-tiktok-uryuryuc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqgqu39I7_ZQ68vwJbAPXfAsR3GG_Ers4',
    appId: '1:571042995828:ios:bf190606ce43ed8931bb21',
    messagingSenderId: '571042995828',
    projectId: 'clone-tiktok-uryuryuc',
    storageBucket: 'clone-tiktok-uryuryuc.appspot.com',
    iosBundleId: 'com.hazka.tiktokClone',
  );
}
